# Generated by Django 2.2.7 on 2019-11-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191110_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
